export const MSG = {
  // Auth
  GOOGLE_AUTH: 'GOOGLE_AUTH',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  LOGOUT: 'LOGOUT',
  GET_AUTH_STATE: 'GET_AUTH_STATE',

  // Session
  UNLOCK: 'UNLOCK',
  LOCK: 'LOCK',
  GET_LOCK_STATE: 'GET_LOCK_STATE',

  // Keystore
  CREATE_KEYPAIR: 'CREATE_KEYPAIR',
  VALIDATE_IMPORT_KEY: 'VALIDATE_IMPORT_KEY',
  COMPLETE_ONBOARDING: 'COMPLETE_ONBOARDING',
  EXPORT_PRIVATE_KEY: 'EXPORT_PRIVATE_KEY',
  DELETE_KEYSTORE: 'DELETE_KEYSTORE',

  // Signing
  SIGN_AND_SUBMIT_TRANSFER_PREAPPROVAL: 'SIGN_AND_SUBMIT_TRANSFER_PREAPPROVAL',
  SIGN_AND_SUBMIT_TRANSFER_TOKEN_STANDARD:
    'SIGN_AND_SUBMIT_TRANSFER_TOKEN_STANDARD',
  SIGN_AND_SUBMIT_APPROVE: 'SIGN_AND_SUBMIT_APPROVE',
  SIGN_AND_SUBMIT_REJECT: 'SIGN_AND_SUBMIT_REJECT',

  // API proxy
  FETCH_BALANCES: 'FETCH_BALANCES',
  FETCH_PRICES: 'FETCH_PRICES',
  PREPARE_TRANSFER_PREAPPROVAL: 'PREPARE_TRANSFER_PREAPPROVAL',
  PREPARE_TRANSFER_TOKEN_STANDARD: 'PREPARE_TRANSFER_TOKEN_STANDARD',
  FETCH_INCOMING_OFFERS: 'FETCH_INCOMING_OFFERS',
  FETCH_OUTGOING_OFFERS: 'FETCH_OUTGOING_OFFERS',
  FETCH_HISTORY_OFFERS: 'FETCH_HISTORY_OFFERS',
  PREPARE_APPROVE: 'PREPARE_APPROVE',
  PREPARE_REJECT: 'PREPARE_REJECT',
  FETCH_ACTIVITY: 'FETCH_ACTIVITY',
  FETCH_ABOUT_ME: 'FETCH_ABOUT_ME',
  REQUEST_FAUCET: 'REQUEST_FAUCET',
} as const;

export type MessageAction = (typeof MSG)[keyof typeof MSG];
